# Data Cleaning with Pandas

In this notebook we'll go through a few basic data cleaning steps that should be performed on all new datasets where necessary.

We'll go through the process with both the `orders` and `orderlines` datasets. You can then practice these skills by cleaning the `products` dataset yourself

In [2]:
import pandas as pd

In [3]:
# orders.csv
url = "https://drive.google.com/file/d/1Vu0q91qZw6lqhIqbjoXYvYAQTmVHh6uZ/view?usp=sharing"
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
orders = pd.read_csv(path)

# orderlines.csv
url = "https://drive.google.com/file/d/1FYhN_2AzTBFuWcfHaRuKcuCE6CWXsWtG/view?usp=sharing"
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
orderlines = pd.read_csv(path)

Before we begin, let's create a copy of the `orders` and `orderlines` DataFrames. This way we are sure any of our changes won't affect the original DataFrames

In [4]:
orders_df = orders.copy()

In [5]:
orderlines_df = orderlines.copy()

In [6]:
orders_df.shape[0]

226909

In [7]:
orders_df

        order_id         created_date  total_paid            state
0         241319  2017-01-02 13:35:40       44.99        Cancelled
1         241423  2017-11-06 13:10:02      136.15        Completed
2         242832  2017-12-31 17:40:03       15.76        Completed
3         243330  2017-02-16 10:59:38       84.98        Completed
4         243784  2017-11-24 13:35:19      157.86        Cancelled
...          ...                  ...         ...              ...
226904    527397  2018-03-14 13:56:38       42.99      Place Order
226905    527398  2018-03-14 13:57:25       42.99  Shopping Basket
226906    527399  2018-03-14 13:57:34      141.58  Shopping Basket
226907    527400  2018-03-14 13:57:41       19.98  Shopping Basket
226908    527401  2018-03-14 13:58:36       18.98      Place Order

[226909 rows x 4 columns]

One of the best ways to begin data cleaning is by exploring using `.info()`. This will tell us:
* The shape of the DataFrame
* The names of the columns
* If there are any missing values
* The datatypes of the columns

By exploring the missing values and correcting any incorrect datatypes, we often come across inconsistencies in our data.

Beyond this, we should also have a **check for any duplicate rows**.

Let's first deal with the duplicates, as it's nice and easy, then we'll explore what `.info()` has to tell us.

## 1.&nbsp; Duplicates
We can check for duplicates using the pandas [.duplicated()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.duplicated.html) method.

We can then delete these rows, if we wish, using [.drop_duplicates()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop_duplicates.html)

In [8]:
# orders_df
orders_df.duplicated().sum()

np.int64(0)

In [9]:
# orderlines_df
orderlines_df.duplicated().sum()

np.int64(0)

We have no duplicate rows in either DataFrame. Easy, there is no problem to solve. Normally though, if there were some duplicates, we'd drop the extra rows.

# 2.&nbsp; `.info()`

In [10]:
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226909 entries, 0 to 226908
Data columns (total 4 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      226909 non-null  int64
 1   created_date  226909 non-null  object
 2   total_paid    226904 non-null  float64
 3   state         226909 non-null  object
dtypes: float64(1), int64(1), object(2)
memory usage: 6.9+ MB

* `total_paid` has 5 missing values
* `created_date` should become datetime datatype

In [11]:
orderlines_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 293983 entries, 0 to 293982
Data columns (total 7 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                293983 non-null  int64
 1   id_order          293983 non-null  int64
 2   product_id        293983 non-null  int64
 3   product_quantity  293983 non-null  int64
 4   sku               293983 non-null  object
 5   unit_price        293983 non-null  object
 6   date              293983 non-null  object
dtypes: int64(4), object(3)
memory usage: 15.7+ MB

* `date` should be a datetime datatype
* `unit_price` should be a float datatype

## 3.&nbsp; Missing values

### 3.1.&nbsp; Orders
* `total_paid` has 5 missing values

In [12]:
orders_df.isna().value_counts()

order_id  created_date  total_paid  state
False     False         False       False    226904
                        True        False         5
Name: count, dtype: int64

In [13]:
orders_df.isna().sum()

order_id        0
created_date    0
total_paid      5
state           0
dtype: int64

In [14]:
num_missing = orders_df['total_paid'].isna().sum()
total_rows = orders_df.shape[0]
percent_missing = (100*num_missing/total_rows)
print(f"5 missing values represents {percent_missing:.5f}% of the rows in our DataFrame")

5 missing values represents 0.00220% of the rows in our DataFrame

> A quick way to find out a percentage if you don't need to print out a sentence for yourself/students/colleagues is `.value_counts(normalize=True)`

In [15]:
orders_df['total_paid'].isna().value_counts()

total_paid
False    226904
True          5
Name: count, dtype: int64

In [16]:
orders_df['total_paid'].isna().value_counts(normalize=True)

total_paid
False    0.999978
True     0.000022
Name: proportion, dtype: float64

In [17]:
orders_df['total_paid'].isna().value_counts(normalize=True)*100

total_paid
False    99.997796
True      0.002204
Name: proportion, dtype: float64

As there is such a tiny amount of missing values, we will simply delete these rows, as we have enough data without them.

In [18]:
orders_df = orders_df.dropna(axis=0)

In [19]:
orders_df = orders_df.loc[~orders.total_paid.isna(), :]#same like dropna

Should you have a significant number of missing values in the future, you have a choice:
+ you can impute the values
+ you can take the values from other DataFrames if they are redundantly stored
+ you can delete the rows or columns
+ or any number of other creative solutions

Please, always consider how much time you have on your project, and what impact your method of choice will have on your final assesment.

### 3.2.&nbsp; Orderlines
There are no missing values in `orderlines_df`

In [20]:
orderlines_df

,id,id_order,product_id,product_quantity,sku,unit_price,date
0,1119109,299539,0,1,OTT0133,18.99,2017-01-01 00:07:19
1,1119110,299540,0,1,LGE0043,399.00,2017-01-01 00:19:45
2,1119111,299541,0,1,PAR0071,474.05,2017-01-01 00:20:57
3,1119112,299542,0,1,WDT0315,68.39,2017-01-01 00:51:40
4,1119113,299543,0,1,JBL0104,23.74,2017-01-01 01:06:38
...,...,...,...,...,...,...,...
293978,1650199,527398,0,1,JBL0122,42.99,2018-03-14 13:57:25
293979,1650200,527399,0,1,PAC0653,141.58,2018-03-14 13:57:34
293980,1650201,527400,0,2,APP0698,9.99,2018-03-14 13:57:41
293981,1650202,527388,0,1,BEZ0204,19.99,2018-03-14 13:58:01
293982,1650203,527401,0,1,APP0927,13.99,2018-03-14 13:58:36

In [21]:
orderlines_df.isna().sum()

id                  0
id_order            0
product_id          0
product_quantity    0
sku                 0
unit_price          0
date                0
dtype: int64

## 4.&nbsp; Datatypes

### 4.1.&nbsp; Orders
* `created_date` should become datetime datatype

In [22]:
orders_df["created_date"] = pd.to_datetime(orders_df["created_date"])

In [23]:
orders_df

        order_id        created_date  total_paid            state
0         241319 2017-01-02 13:35:40       44.99        Cancelled
1         241423 2017-11-06 13:10:02      136.15        Completed
2         242832 2017-12-31 17:40:03       15.76        Completed
3         243330 2017-02-16 10:59:38       84.98        Completed
4         243784 2017-11-24 13:35:19      157.86        Cancelled
...          ...                 ...         ...              ...
226904    527397 2018-03-14 13:56:38       42.99      Place Order
226905    527398 2018-03-14 13:57:25       42.99  Shopping Basket
226906    527399 2018-03-14 13:57:34      141.58  Shopping Basket
226907    527400 2018-03-14 13:57:41       19.98  Shopping Basket
226908    527401 2018-03-14 13:58:36       18.98      Place Order

[226904 rows x 4 columns]

In [24]:
orders_cl=orders_df.copy()
orders_cl.info()

<class 'pandas.core.frame.DataFrame'>
Index: 226904 entries, 0 to 226908
Data columns (total 4 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      226904 non-null  int64
 1   created_date  226904 non-null  datetime64[ns]
 2   total_paid    226904 non-null  float64
 3   state         226904 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 8.7+ MB

### 4.1.&nbsp; Orderlines
* `date` should be a datetime datatype
* `unit_price` should be a float datatype

#### 4.1.1.&nbsp; `date`

In [25]:
orderlines_df["date"] = pd.to_datetime(orderlines_df["date"])

#### 4.1.2.&nbsp;`unit_price`

As you can see when we try to convert `unit_price` to a numerical datatype, we receive a `ValueError` telling us that pandas doesn't understand the number `1.137.99`. This is probably because numbers cannot have multiple decimal points. Let's see if there are any other numbers like this:

> `.` is a wildcard in regex, we need the `\` as an escape

In [26]:
# orderlines_df["unit_price"] = pd.to_numeric(orderlines_df["unit_price"])

In [27]:
orderlines_df.unit_price.str.contains("\d+\.\d+\.\d+").value_counts()

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_249/3763006858.py:1: SyntaxWarning: invalid escape sequence '\d'
  orderlines_df.unit_price.str.contains("\d+\.\d+\.\d+").value_counts()

unit_price
False    257814
True      36169
Name: count, dtype: int64

In [28]:
orderlines_df.loc[orderlines_df['unit_price'].str.count(r'\.')>1]

,id,id_order,product_id,product_quantity,sku,unit_price,date
6,1119115,299544,0,1,APP1582,1.137.99,2017-01-01 01:17:21
11,1119126,299549,0,1,PAC0929,2.565.99,2017-01-01 02:07:42
15,1119131,299553,0,1,APP1854,3.278.99,2017-01-01 02:14:47
43,1119195,299582,0,1,PAC0961,2.616.99,2017-01-01 08:54:00
59,1119214,299596,0,1,PAC1599,2.873.99,2017-01-01 09:53:11
...,...,...,...,...,...,...,...
293862,1649999,452946,0,1,APP2075,2.999.00,2018-03-14 13:03:33
293887,1650045,527321,0,1,PAC2148,3.497.00,2018-03-14 13:10:15
293889,1650050,527324,0,1,PAC2117,3.075.00,2018-03-14 13:10:56
293911,1650088,527342,0,1,APP2492,1.329.00,2018-03-14 13:24:51
293936,1650135,527364,0,1,APP2491,1.329.00,2018-03-14 13:36:13

In [29]:
# Count the number of decimal points in the unit_price
orderlines_df['unit_price'].str.count("\.").value_counts()

<>:2: SyntaxWarning: invalid escape sequence '\.'
<>:2: SyntaxWarning: invalid escape sequence '\.'
/tmp/ipykernel_249/2537486199.py:2: SyntaxWarning: invalid escape sequence '\.'
  orderlines_df['unit_price'].str.count("\.").value_counts()

unit_price
1    257814
2     36169
Name: count, dtype: int64

Looks like over 36000 rows in `orderlines` are affected by this problem. Let's work out how much that is as a percentage of our total data.

In [30]:
# Count the rows with more than one `.`
mult_decimal_rows = (orderlines_df['unit_price'].str.count("\.")>1).sum()

# Find the percentage of corrupted rows
percent_corrupted = (100 * mult_decimal_rows / orderlines_df.shape[0])
print(f"{percent_corrupted:.2f}% of the rows in our DataFrame have multiple decimal points in the unit_price")

<>:2: SyntaxWarning: invalid escape sequence '\.'
<>:2: SyntaxWarning: invalid escape sequence '\.'
/tmp/ipykernel_249/2770637137.py:2: SyntaxWarning: invalid escape sequence '\.'
  mult_decimal_rows = (orderlines_df['unit_price'].str.count("\.")>1).sum()

12.30% of the rows in our DataFrame have multiple decimal points in the unit_price

This is a bit of a tricky decision as 12.3% is a significant amount of our data... and we might even end up losing a larger portion of our data than this too. For the moment we will delete the rows as we only have 2 weeks for this project and I'd like some quick, accurate results to show. If we have time at the end, we can come back and investigate this problem further, maybe there's a solution?

Each row of `orderlines` represents a product in an order. For example, if order number 175 contained 3 seperate products, then order 175 would have 3 rows in `orderlines`, one row for each of the products. If 2 of those products have 'normal' prices (14.99, 15.85) and 1 has a price with 2 decimal points (1.137.99), we need to remove the whole order and not just the affected row. If we only remove the row with 2 decimal places then any later analysis about products and prices could be misleading.

We therefore need to find the order numbers associated with the rows that have 2 decimal points, and then remove all the associated rows.

In [31]:
# two_dot_order_ids_list = orderlines_df.loc[orderlines_df.unit_price.str.contains("\d+\.\d+\.\d+"), "id_order"]

# orderlines_df = orderlines_df.loc[~orderlines_df.id_order.isin(two_dot_order_ids_list)]

In [32]:
# Boolean mask to find the orders that contain a price with multiple decimal points
# multiple_decimal_mask = orderlines_df['unit_price'].str.count("\.") > 1

# Apply the boolean mask to the orderlines DataFrame. This way we can find the order_id of all the affected orders.
# corrupted_order_ids = orderlines_df.loc[multiple_decimal_mask, "id_order"]

# Keep only the rows that do not have multiple decimal points
# orderlines_df = orderlines_df.loc[~orderlines_df['id_order'].isin(corrupted_order_ids)]

In [33]:
orderlines_df.shape[0]

293983

In [34]:
orderlines_df.sample(70)

,id,id_order,product_id,product_quantity,sku,unit_price,date
65858,1248886,356317,0,1,APP1971,519.00,2017-05-16 15:37:51
159969,1433776,436587,0,1,PLA0027,66.49,2017-11-24 09:04:17
69649,1255746,359477,0,1,SAN0045,10.99,2017-05-26 18:14:20
122371,1362539,404992,0,1,WDT0183,140.58,2017-09-26 18:38:51
16295,1157057,313942,0,1,LEX0039,49.99,2017-01-23 18:12:32
...,...,...,...,...,...,...,...
29914,1184158,325681,0,1,APP0409,79.99,2017-02-17 14:55:20
87078,1286277,374429,0,1,TPL0012-A,22.79,2017-07-08 01:17:25
243120,1568943,493920,0,1,APP0662,138.00,2018-01-18 15:32:10
278456,1626057,516978,0,1,MMW0016,22.99,2018-02-24 23:09:03
14612,1153626,312559,0,1,PAC0185,1.469.00,2017-01-20 14:11:43

We still have 216250 rows in orderlines to work with. This should be more than enough for our evaluation.

Now that all of the 2 decimal point prices have been removed, let's try again to convert the column `unit_price` to the correct datatype.

I would like to remove the first place decimal because the pattern looks like the first decimal is an error. Looks fine when I remove the first decimal.

In [35]:
orderlines_df['unit_price'] = orderlines_df['unit_price'].astype(str).str.replace(r'\.(?=.*\.)', '', regex=True)
orderlines_df['unit_price']
orderlines_df.sample(10)

,id,id_order,product_id,product_quantity,sku,unit_price,date
94881,1300645,381222,0,1,CRU0026-2,112.49,2017-07-24 09:42:48
56487,1232741,336756,0,1,APP1215,91.73,2017-04-21 16:27:27
272420,1615633,512340,0,1,PAC2285,329.42,2018-02-16 00:40:55
268453,1608967,509382,0,1,BEL0190,12.99,2018-02-10 18:12:26
214583,1519698,473265,0,2,WDT0183,129.20,2017-12-27 18:25:25
189805,1479470,456348,0,1,APP1216,130.00,2017-12-06 18:36:07
205819,1502995,465868,0,1,APP2488,881.82,2017-12-18 16:29:27
81224,1275900,369466,0,1,PAC0023,65.99,2017-06-27 11:34:26
125081,1367457,407358,0,1,LIF0103,34.19,2017-10-02 13:47:55
150967,1418546,430286,0,1,PHI0062,24.90,2017-11-21 14:39:42

In [36]:
orderlines_df.loc[orderlines_df['unit_price'].str.count(r'\.')>1]
#now we don't have any two decimals digits

Empty DataFrame
Columns: [id, id_order, product_id, product_quantity, sku, unit_price, date]
Index: []

In [37]:
orderlines_df.duplicated().sum()

np.int64(0)

In [38]:
orderlines_df['unit_price']= pd.to_numeric(orderlines_df['unit_price'])

In [39]:
orderlines_df["unit_price"].dtype

dtype('float64')

In [40]:
orderlines_df

,id,id_order,product_id,product_quantity,sku,unit_price,date
0,1119109,299539,0,1,OTT0133,18.99,2017-01-01 00:07:19
1,1119110,299540,0,1,LGE0043,399.00,2017-01-01 00:19:45
2,1119111,299541,0,1,PAR0071,474.05,2017-01-01 00:20:57
3,1119112,299542,0,1,WDT0315,68.39,2017-01-01 00:51:40
4,1119113,299543,0,1,JBL0104,23.74,2017-01-01 01:06:38
...,...,...,...,...,...,...,...
293978,1650199,527398,0,1,JBL0122,42.99,2018-03-14 13:57:25
293979,1650200,527399,0,1,PAC0653,141.58,2018-03-14 13:57:34
293980,1650201,527400,0,2,APP0698,9.99,2018-03-14 13:57:41
293981,1650202,527388,0,1,BEZ0204,19.99,2018-03-14 13:58:01
293982,1650203,527401,0,1,APP0927,13.99,2018-03-14 13:58:36

In [41]:
orderlines_cl=orderlines_df.copy()
orderlines_cl

,id,id_order,product_id,product_quantity,sku,unit_price,date
0,1119109,299539,0,1,OTT0133,18.99,2017-01-01 00:07:19
1,1119110,299540,0,1,LGE0043,399.00,2017-01-01 00:19:45
2,1119111,299541,0,1,PAR0071,474.05,2017-01-01 00:20:57
3,1119112,299542,0,1,WDT0315,68.39,2017-01-01 00:51:40
4,1119113,299543,0,1,JBL0104,23.74,2017-01-01 01:06:38
...,...,...,...,...,...,...,...
293978,1650199,527398,0,1,JBL0122,42.99,2018-03-14 13:57:25
293979,1650200,527399,0,1,PAC0653,141.58,2018-03-14 13:57:34
293980,1650201,527400,0,2,APP0698,9.99,2018-03-14 13:57:41
293981,1650202,527388,0,1,BEZ0204,19.99,2018-03-14 13:58:01
293982,1650203,527401,0,1,APP0927,13.99,2018-03-14 13:58:36

It worked perfectly

# Challenge: Clean the `products` DataFrame
Now it's your turn. Use the lessons you learnt above and clean the products DataFrame. You don't have to copy exactly what we did. Think about the consequences of your actions, sometimes it is ok to delete rows, other times you may wish to come up with more creative solutions.

In [42]:
# products.csv
url = "https://drive.google.com/file/d/1afxwDXfl-7cQ_qLwyDitfcCx3u7WMvkU/view?usp=sharing"
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
products = pd.read_csv(path)

In [43]:
# your code here
products_df=products.copy()
products_df

,sku,name,desc,price,promo_price,in_stock,type
0,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,499.899,1,8696
1,APP0023,Apple Mac Keyboard Keypad Spanish,USB ultrathin keyboard Apple Mac Spanish.,59,589.996,0,13855401
2,APP0025,Mighty Mouse Apple Mouse for Mac,mouse Apple USB cable.,59,569.898,0,1387
3,APP0072,Apple Dock to USB Cable iPhone and iPod white,IPhone dock and USB Cable Apple iPod.,25,229.997,0,1230
4,KIN0007,Mac Memory Kingston 2GB 667MHz DDR2 SO-DIMM,2GB RAM Mac mini and iMac (2006/07) MacBook Pr...,34.99,31.99,1,1364
...,...,...,...,...,...,...,...
19321,BEL0376,Belkin Travel Support Apple Watch Black,compact and portable stand vertically or horiz...,29.99,269.903,1,12282
19322,THU0060,"Enroute Thule 14L Backpack MacBook 13 ""Black",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392
19323,THU0061,"Enroute Thule 14L Backpack MacBook 13 ""Blue",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392
19324,THU0062,"Enroute Thule 14L Backpack MacBook 13 ""Red",Backpack with capacity of 14 liter compartment...,69.95,649.903,0,1392
19325,THU0063,"Enroute Thule 14L Backpack MacBook 13 ""Green",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392

In [44]:
products_df.shape[0]

19326

### Look for Duplicates

In [45]:
# your code here
products_df.duplicated().sum()

np.int64(8746)

### Look for Missing values

In [46]:
products_df.isna().sum()

sku             0
name            0
desc            7
price          46
promo_price     0
in_stock        0
type           50
dtype: int64

In [47]:
products_df.isna().value_counts(normalize=True)

sku    name   desc   price  promo_price  in_stock  type
False  False  False  False  False        False     False    0.994670
                                                   True     0.002587
                     True   False        False     False    0.002380
              True   False  False        False     False    0.000362
Name: proportion, dtype: float64

In [48]:
products_df['desc'].isna().value_counts()

desc
False    19319
True         7
Name: count, dtype: int64

In [49]:
products_df['price'].isna().value_counts()

price
False    19280
True        46
Name: count, dtype: int64

In [50]:
products_df['type'].isna().value_counts()

type
False    19276
True        50
Name: count, dtype: int64

### Check / Change Data types

In [51]:
# your code here
products_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19326 entries, 0 to 19325
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sku          19326 non-null  object
 1   name         19326 non-null  object
 2   desc         19319 non-null  object
 3   price        19280 non-null  object
 4   promo_price  19326 non-null  object
 5   in_stock     19326 non-null  int64
 6   type         19276 non-null  object
dtypes: int64(1), object(6)
memory usage: 1.0+ MB

In [52]:
products_df.duplicated().sum()

np.int64(8746)

In [53]:
products_df = products_df.drop_duplicates()

In [54]:
products_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10580 entries, 0 to 19325
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sku          10580 non-null  object
 1   name         10580 non-null  object
 2   desc         10573 non-null  object
 3   price        10534 non-null  object
 4   promo_price  10580 non-null  object
 5   in_stock     10580 non-null  int64
 6   type         10530 non-null  object
dtypes: int64(1), object(6)
memory usage: 661.2+ KB

In [55]:
products_df.duplicated().sum()
#now we don't have duplicates but check again !!!

np.int64(0)

In [56]:
products_df.duplicated(subset="sku").sum()

np.int64(1)

In [57]:
products_df.loc[products_df.duplicated(subset="sku", keep=False)]

,sku,name,desc,price,promo_price,in_stock,type
7992,APP1197,"Apple iMac 21.5 ""Core i5 31 GHz Retina display...",Desktop Apple iMac 21.5 inch i5 31 GHz Retina ...,1729,1305.59,0,1282
8000,APP1197,"Apple iMac 21.5 ""Core i5 31 GHz Retina display...",Desktop Apple iMac 21.5 inch i5 31 GHz Retina ...,NaN,1305.59,0,1282

In [58]:
products_df['sku'].nunique()

10579

In [59]:
len(products_df)

10580

In [60]:
products_df[products_df['sku'].duplicated(keep=False)]

,sku,name,desc,price,promo_price,in_stock,type
7992,APP1197,"Apple iMac 21.5 ""Core i5 31 GHz Retina display...",Desktop Apple iMac 21.5 inch i5 31 GHz Retina ...,1729,1305.59,0,1282
8000,APP1197,"Apple iMac 21.5 ""Core i5 31 GHz Retina display...",Desktop Apple iMac 21.5 inch i5 31 GHz Retina ...,NaN,1305.59,0,1282

In [61]:
products_df['sku'].value_counts()[products_df['sku'].value_counts() > 1]

sku
APP1197    2
Name: count, dtype: int64

In [62]:
products_df = products_df.dropna(subset=['price']).drop_duplicates(subset='sku')
# drops rows with all price = NaN value too
# alternative
# products_df = products_df.loc[~products['price'].isna()]
# products_df = products_df.dropna(subset=['price'])

In [63]:
products_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10534 entries, 0 to 19325
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sku          10534 non-null  object
 1   name         10534 non-null  object
 2   desc         10527 non-null  object
 3   price        10534 non-null  object
 4   promo_price  10534 non-null  object
 5   in_stock     10534 non-null  int64
 6   type         10484 non-null  object
dtypes: int64(1), object(6)
memory usage: 658.4+ KB

In [64]:
products_df[products_df['price'].isna()]

Empty DataFrame
Columns: [sku, name, desc, price, promo_price, in_stock, type]
Index: []

In [65]:
products_df['sku'].value_counts()[products_df['sku'].value_counts() > 1]
#now the duplicated sku is also dropped

Series([], Name: count, dtype: int64)

In [66]:
products_df[products_df['sku'] == 'APP1197']

,sku,name,desc,price,promo_price,in_stock,type
7992,APP1197,"Apple iMac 21.5 ""Core i5 31 GHz Retina display...",Desktop Apple iMac 21.5 inch i5 31 GHz Retina ...,1729,1305.59,0,1282

In [67]:
products_df.shape[0]
# we come down from 19326 to 10534 rows

10534

In [68]:
products_df.loc[products_df["price"].astype(str).str.count(r"\.") > 1]

,sku,name,desc,price,promo_price,in_stock,type
665,CRU0015-2,Crucial memory Mac 16GB (2x8GB) SO-DIMM DDR3 1...,RAM 16GB (2x8GB) 135V MacBook Pro iMac (2012/2...,1.639.792,1.629.894,1,1364
792,APP0672,Apple iPhone 5S 16GB Space Gray,New iPhone 5S 16G Libre (ME432Y / AB).,4.694.994,4.694.994,0,NaN
797,APP0673,Apple iPhone 5S 16GB Silver,New Free iPhone 5S 16GB (ME433Y / A).,4.090.042,4.090.042,0,NaN
827,PAC0339,NewerTech miniStack 4TB Hard Drive Mac,External Box Hard Drive Mac + 4TB.,2.199.791,2.199.901,0,11935397
885,PAC0376,OWC Mercury Elite Pro Dual Thunderbolt + 8TB,RAID outer box 35 inch SATA connection Thunder...,5.609.698,5.549.895,0,11935397
...,...,...,...,...,...,...,...
19312,REP0424,Input repair Headphones iPad,Repair service including parts and labor for iPad,6.999.003,69.99,0,"1,44E+11"
19313,REP0421,iPad charging connector repair,Repair service including parts and labor for iPad,6.999.003,69.99,0,"1,44E+11"
19314,REP0416,iPad front camera repair,Repair service including parts and labor for iPad,6.999.003,69.99,0,"1,44E+11"
19315,REP0413,repair rear camera iPad,Repair service including parts and labor for iPad,6.999.003,69.99,0,"1,44E+11"
19316,REP0407,iPad battery repair,Repair service including parts and labor for iPad,6.999.003,69.99,0,"1,44E+11"

In [69]:
products_df.loc[products_df["promo_price"].astype(str).str.count(r"\.") > 1]

,sku,name,desc,price,promo_price,in_stock,type
50,APP0367,Apple Mini DisplayPort to DVI Adapter Mac dual...,Adapter Mini Display Port to DVI dual channel ...,119,1.119.976,0,1325
51,APP0344,"Apple Thunderbolt Display 27 ""Monitor Mac",Monitor Display 27-inch Apple Thunderbolt (MC9...,1149,10.449.923,0,1296
66,MAK0008,Maclocks theft case iPad 2 3 and 4 black with ...,Case antitheft iPad 2 3 and 4 polycarbonate ro...,120,1.199.957,0,12635403
67,MAK0007,Maclocks theft case iPad 2 3 and 4 transparent...,Case antitheft iPad 2 3 and 4 polycarbonate ro...,120,1.079.961,0,12635403
97,MAK0014,Maclocks safety housing Kiosk iPad 2 3 and 4 b...,Holder and housing iPad 2 3 and 4 aluminum and...,164.99,1.649.896,0,1216
...,...,...,...,...,...,...,...
19300,REP0412,Rear Camera Repair iPhone 7 Plus,It is including parts and labor for iPhone 7 Plus,119.99,1.199.897,0,"1,44E+11"
19317,REP0403,iPad LCD screen repair,Repair service including parts and labor for iPad,159.99,1.599.898,0,"1,44E+11"
19318,REP0402,iPad touch screen repair,Repair service including parts and labor for iPad,139.99,1.399.897,0,"1,44E+11"
19319,KNO0032,"Knomo MacBook Pro Beauchamp Backpack 14 ""Black",Backpack thin nylon mesh internal compartment ...,179,1.699.905,1,1392
19320,REP0076,repair Full screen iPad (1st generation),Repair service including parts and labor for iPad,149.99,1.499.795,0,"1,44E+11"

In [70]:
pd.set_option('display.max_columns', None)

# pd.set_option('display.max_colwidth', 100) # to increase the width of the columns
#pd.reset_option('display.max_colwidth')#to reset the display
# pd.reset_option('all')

```We can clearly see the price and promo_price both have unusual numbers with two decimals and 3 digits after decimals. We have to figure out what is the best way to deal with those values!!!```

In [71]:
products_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10534 entries, 0 to 19325
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sku          10534 non-null  object
 1   name         10534 non-null  object
 2   desc         10527 non-null  object
 3   price        10534 non-null  object
 4   promo_price  10534 non-null  object
 5   in_stock     10534 non-null  int64
 6   type         10484 non-null  object
dtypes: int64(1), object(6)
memory usage: 658.4+ KB

In [72]:
products_df["desc"].isna().sum()

np.int64(7)

In [73]:
products_df.loc[products_df['desc'].isna(), :]

,sku,name,desc,price,promo_price,in_stock,type
16126,WDT0211-A,"Open - Purple 2TB WD 35 ""PC Security Mac hard ...",NaN,107,814.659,0,1298
16128,APP1622-A,Open - Apple Smart Keyboard Pro Keyboard Folio...,NaN,1.568.206,1.568.206,0,1298
17843,PAC2334,Synology DS718 + NAS Server | 10GB RAM,NaN,566.35,5.659.896,0,12175397
18152,KAN0034-A,Open - Kanex USB-C Gigabit Ethernet Adapter Ma...,NaN,29.99,237.925,0,1298
18490,HTE0025,Hyper Pearl 1600mAh battery Mini USB Mirror an...,NaN,24.99,22.99,1,1515
18612,OTT0200,OtterBox External Battery Power Pack 20000 mAHr,NaN,79.99,56.99,1,1515
18690,HOW0001-A,Open - Honeywell thermostat Lyric zonificador ...,NaN,199.99,1.441.174,0,11905404

7 is a very small number to have missing, let's have a closer look

We have 2 choices here:

We can quickly and easily remove these rows.
Or, alternatively, the products names here are quite descriptive, so I'm tempted to just copy them to the description column, so that there is a description if we later want to utilise this column. I wouldn't recommend this if this DataFrame was the source of truth for our website. But this is not the case here, and we're not faking any information (guessing a price or so), so I'm happy with this option

In [74]:

products_df['desc']=products_df['desc'].fillna( products_df['name'])
# alternative
# products_df.loc[products_df['desc'].isna(), 'desc'] = products_df.loc[products_df['desc'].isna(), 'name']

In [75]:
products_df.loc[products_df['desc'].isna(), :]

Empty DataFrame
Columns: [sku, name, desc, price, promo_price, in_stock, type]
Index: []

Did you also notice above that we have the dreaded two decimal point problem in both the `price` and `promo_price` columns? We can also see prices with 3 decimal places, prices should have 2 decimal places: this gives us more cause for concern


We saw from looking at the output of `.info()` that both `price` and `promo_price` have been stored as objects and not as a numerical datatypes. We also saw while solving other problems that both columns have some prices with 3 decimal places and others with 2 decimal points - the latter will prevent us from converting the datatype to numerical, so first we must investigate and solve these problems.

First, let's see how many values are affected by the 2-decimal-dot problems or 3 decimal places.

In [76]:
# from ast import Or
products_df.loc[(products_df.price.str.contains(r"\d+\.\d+\.\d+"))|(products_df.price.str.contains(r"\d+\.\d{3,}")), :]

,sku,name,desc,price,promo_price,in_stock,type
362,REP0043,Speaker lower repair iPhone 4,Repair service including parts and labor for i...,499.004,499.004,0,"1,44E+11"
480,PIE0011,Internal Battery for iPhone 3G,Replacement AC Adapter for Apple iPhone 3G.,98.978,98.978,0,21485407
515,SEN0061,Sennheiser EZX 80 Handsfree iPhone iPad and iP...,IPhone bluetooth headset with microphone iPad ...,649.891,649.891,0,5384
518,SEV0026,Service installation RAM + HDD + SSD MacBook /...,RAM + HDD installation + SSD in your MacBook /...,599.918,599.918,0,20642062
525,SEV0024,Service installation RAM + HDD + SSD Mac mini,installation RAM HDD + SSD + on your Mac mini ...,599.918,599.918,0,20642062
...,...,...,...,...,...,...,...
19312,REP0424,Input repair Headphones iPad,Repair service including parts and labor for iPad,6.999.003,69.99,0,"1,44E+11"
19313,REP0421,iPad charging connector repair,Repair service including parts and labor for iPad,6.999.003,69.99,0,"1,44E+11"
19314,REP0416,iPad front camera repair,Repair service including parts and labor for iPad,6.999.003,69.99,0,"1,44E+11"
19315,REP0413,repair rear camera iPad,Repair service including parts and labor for iPad,6.999.003,69.99,0,"1,44E+11"
19316,REP0407,iPad battery repair,Repair service including parts and labor for iPad,6.999.003,69.99,0,"1,44E+11"

In [77]:
products_df.loc[(products_df.price.str.contains(r"\d+\.\d+\.\d+"))|(products_df.price.str.contains(r"\d+\.\d{3,}")), :].shape#[0]

(542, 7)

In [78]:
price_problems_number = products_df.loc[(products_df.price.str.contains(r"\d+\.\d+\.\d+"))|(products_df.price.str.contains(r"\d+\.\d{3,}")), :].shape[0]
price_problems_number

542

In [79]:
print(f"The column price has in total {price_problems_number} wrong values. This is {round(((price_problems_number / products_df.shape[0]) * 100), 2)}% of the rows of the DataFrame")

The column price has in total 542 wrong values. This is 5.15% of the rows of the DataFrame

5.15% is a reasonable amount of our data. However, the price column will be important to understanding discounts, so I'd like it to be very trustworthy as we are basing business decisions on it. Therefore, we'll delete these rows.

In [80]:
products_df = products_df.loc[~((products_df.price.str.contains(r"\d+\.\d+\.\d+"))|(products_df.price.str.contains(r"\d+\.\d{3,}"))), :]

In [81]:
products_df

,sku,name,desc,price,promo_price,in_stock,type
0,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,499.899,1,8696
1,APP0023,Apple Mac Keyboard Keypad Spanish,USB ultrathin keyboard Apple Mac Spanish.,59,589.996,0,13855401
2,APP0025,Mighty Mouse Apple Mouse for Mac,mouse Apple USB cable.,59,569.898,0,1387
3,APP0072,Apple Dock to USB Cable iPhone and iPod white,IPhone dock and USB Cable Apple iPod.,25,229.997,0,1230
4,KIN0007,Mac Memory Kingston 2GB 667MHz DDR2 SO-DIMM,2GB RAM Mac mini and iMac (2006/07) MacBook Pr...,34.99,31.99,1,1364
...,...,...,...,...,...,...,...
19321,BEL0376,Belkin Travel Support Apple Watch Black,compact and portable stand vertically or horiz...,29.99,269.903,1,12282
19322,THU0060,"Enroute Thule 14L Backpack MacBook 13 ""Black",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392
19323,THU0061,"Enroute Thule 14L Backpack MacBook 13 ""Blue",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392
19324,THU0062,"Enroute Thule 14L Backpack MacBook 13 ""Red",Backpack with capacity of 14 liter compartment...,69.95,649.903,0,1392
19325,THU0063,"Enroute Thule 14L Backpack MacBook 13 ""Green",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392

To complete our task, let's convert the column to a numeric datatype

In [82]:
products_df["price"] = pd.to_numeric(products_df["price"])

In [83]:
products_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9992 entries, 0 to 19325
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sku          9992 non-null   object
 1   name         9992 non-null   object
 2   desc         9992 non-null   object
 3   price        9992 non-null   float64
 4   promo_price  9992 non-null   object
 5   in_stock     9992 non-null   int64
 6   type         9946 non-null   object
dtypes: float64(1), int64(1), object(5)
memory usage: 624.5+ KB

In [84]:
#checking for duplicated sku
products_df['sku'].duplicated().sum()

np.int64(0)

For ```promo_price```Again, let's begin by seeing how many values are affected by the 2-decimal-dots problem, or the 3 decimal-places problem

In [85]:
promo_problems_number = products_df.loc[(products_df.promo_price.str.contains(r"\d+\.\d+\.\d+"))|(products_df.promo_price.str.contains(r"\d+\.\d{3,}")), :].shape[0]
promo_problems_number

9232

In [86]:
print(f"The column promo_price has in total {promo_problems_number} wrong values. This is {round(((promo_problems_number / products_df.shape[0]) * 100), 2)}% of the rows of the DataFrame")

The column promo_price has in total 9232 wrong values. This is 92.39% of the rows of the DataFrame

WOW!!! That's a lot of wrong data. Let's have a quick investigate to check that's correct. We'll make a DataFrame by copy-pasting the code we used above and then look at a large sample to check that all the numbers in the `promo_price` column really have either 2 decimal points or 3 decimal places.

In [87]:
promo_price_df = products_df.loc[(products_df.promo_price.str.contains(r"\d+\.\d+\.\d+"))|(products_df.promo_price.str.contains(r"\d+\.\d{3,}")), :]
promo_price_df.sample(50)

,sku,name,desc,price,promo_price,in_stock,type
13355,APP1651,Apple iPhone 7 128GB Gold Rosa,New Apple iPhone 7 128GB Rose Gold free,749.00,7.340.005,0,85641716
77,WAC0046,Intuos Wacom stylus ArtPen 5/4,special stylus Mac and PC for Intuos4 graphics...,109.90,999.944,0,1229
12022,SAN0131,SanDisk Extreme SDXC Memory Card UHS Class 3 |...,Memory card SDXC UHS Class 3 120GB speeds 90MB...,69.99,502.803,0,57445397
15811,WAC0157-A,Open - Wacom Cintiq Interactive Pen & Touch 27...,Professional graphics tablet touch screen with...,2549.90,18.048.615,0,1298
1583,LAC0147,LaCie d2 USB 3.0 hard disk 5TB,External Hard Disk 1 bay for Mac and PC.,229.00,1.937.936,0,11935397
14832,STA0040,Startech USB Hub Charger-C to HDMI 4K 2 USB 3....,Hub Thunderbolt connection 3 / USB to HDMI 4K-...,146.99,1.099.902,1,12585395
18937,OWC0210-A,Open - OWC Data Doubler Optical Bay Adapter Ki...,Reconditioned replacement tray SuperDrive or S...,72.99,271.549,0,12755395
13167,SYN0152,Synology RackStation NAS RS3617RPxs,12-bay NAS server Enterprise 8GB memory for Ma...,3392.73,33.569.877,0,12175397
15501,SAN0110-A,Open - Sandisk Wireless Connect Wireless Flash...,Wireless Storage 128GB for iPhone / iPad / Mac,104.00,562.051,0,1298
16415,APP2279,"Apple MacBook Pro 13 ""Core i5 Touch Bar 33GHz ...",New MacBook Pro 13-inch Core i5 Touch Bar 33 G...,2609.00,24.520.045,0,"1,02E+12"
18586,APP2092-A,Open - Apple iPhone Silicone Case Cover 7 plus...,Ultrathin silicone case and microfiber premium...,45.00,389.995,0,11865403
894,FIT0022,Bracelet Flex fitbit activity monitor orange,Control activity bracelet with two interchange...,99.99,899.877,0,11905404
983,JAB0035,Jabra Wireless Speaker Max solmate,Dolby wireless bluetooth speaker with NFC tech...,399.95,2.998.985,0,5398
13448,TUC0288,ELEKTRO FLEX Tucano iPhone UltraSlim Case 8 Pl...,thin flexible sleeve with metallic shades for ...,19.90,169.896,0,11865403
13709,BOS0045,SoundTrue Bose Headphones Black Carbon Ultra IFM,Water resistant headphones indoor StayHear Ult...,129.00,1.159.906,0,5384
2720,SYN0120,Synology RXD1215sas expansion module for Mac a...,Expansion unit 12 RackStation bays.,3299.98,32.998.999,0,12175397
2314,LOG0160,Logitech AnyAngle iPad Mini Case with Stand Gray,Cover with multiposition support for iPad Mini...,71.99,468.996,0,12635403
19160,BNQ0061-A,"Open - EW2775ZH Monitor Benq 27 ""FHD HDMI",Reconditioned screen with HDMI BenQ 27-inch fo...,189.00,1.788.947,0,1296
18278,FIT0062,Fitbit Smartwatch Ionic Gray,Fitbit is the sports Smartwatch Ionic waterpro...,349.95,3.399.894,1,11905404
17193,OWC0197,Mac OWC Memory 32GB 1333MHz DIMM,RAM 32GB Mac Pro 2010-2012,345.99,3.239.896,1,1364
12326,UAG0012-A,(Open) Urban Armor Gear Composite Case Cover i...,resistant cover bumps and drops for iPhone 6 P...,34.99,182.774,0,1298
10897,PAC1401,QNAP TS-453mini | 8GB RAM Mac and PC Server Nas,8-bay NAS Server for Mac and PC.,709.99,5.799.905,0,12175397
2417,FCM0009,FCM Mac Memory 4GB DDR3 1066MHz SO-DIMM,4GB RAM Mac mini iMac MacBook and MacBook Pro ...,43.99,429.889,0,1364
355,KEN0059,Kensington Soft Case cover iPhone 5 / 5S black,Soft Case iPhone 5 / 5S.,14.99,89.903,0,11865403
18918,APP2613,Correa Apple Nike Sport 38mm Pure Platinum / B...,Nike belt shrunk for Apple Watch 38mm,59.00,569.995,0,2449
709,APP0811,Apple Mac Pro six cores 35GHz | 16GB RAM | 512...,New Mac Pro with 16GB of RAM 6 cores and 1TB F...,5609.00,52.795.845,0,1282
11358,CRU0015-A,Open - Memory Crucial 8GB Mac DDR3 1600MHZ SO-...,RAM 8GB 135V / 15V MacBook Pro iMac (2013) Mac...,79.99,799.895,0,1298
10893,QNA0137,QNAP TVS + -863 | 16GB RAM Mac and PC Server Nas,8-bay NAS Server for Mac and PC.,1511.29,15.109.899,0,12175397
17661,APP2533,Apple iPhone Leather Skin Case Cover 8/7 Rosa ...,ultrathin leather case and microfiber premium ...,55.00,519.998,0,11865403
1024,STA0016,Startech Mini DisplayPort to DisplayPort Cable...,Adapdator Cable Mini Display Port Male to Disp...,12.99,99.898,0,1325
253,PAC1241,"Apple MacBook Pro 133 ""i7 29GHz | RAM 16GB | 5...",Apple MacBook Pro 133 inches (MD101Y / A) with...,2399.00,23.989.896,0,1282
15217,BEZ0172-A,Open - Be.ez LArobe MacBook Pro Retina ONE sle...,Neoprene Sleeve for MacBook Pro Retina 13 inches,29.95,198.695,0,1298
14473,WAC0217,"Wacom MobileStudio Pro 13 ""i7 512GB",Professional graphics tablet with 13-inch i7 a...,2699.90,26.055.946,0,1405
15950,LAC0224-A,Open - Lacie d2 Hard Drive 10TB Thunderbolt 3,10TB external hard drive designed to work 24x7...,629.00,470.577,0,1298
1792,MIP0015,Mipow Playbulb LED bulb with candle light,LED light bulb with customizable candle.,49.99,199.892,0,11905404
13211,PAC1520,Pack QNAP TS-451A NAS 2GB RAM l l 24TB (4x6TB)...,NAS with 2GB of RAM and 4 HDDs 6TB for Mac and PC,1466.99,11.773.675,1,12175397
1336,SPE0128,Candishell Speck Case iPhone 6 White / Dark Gray,ultra resistant iPhone 6. Housing,24.99,219.857,0,11865403
11120,JMO0085,Just Mobile charging base Apple Watch Black Ti...,Load bearing aluminum Apple Watch.,44.95,329.894,1,24215399
13007,LAC0188,LaCie Porsche Design Hard Drive 4TB USB-C and ...,Desktop Hard Drive 4TB USB-C adapter cable con...,179.99,1.449.943,1,11935397
15679,SXA0039,SecurityXtra One Security Support adjustable i...,Adjustable safety support wall anchor iPad,199.99,1.299.903,0,1216
17507,TUC0344,Denso Tucano iPhone Case Black Mil-Std X,military-grade protection without sacrificing ...,26.90,249.901,1,11865403
13144,SPE0181,Speck Pocket VR virtual reality glasses + Cand...,Virtual reality goggles + Protective Case for ...,69.95,549.897,1,11865403
13649,GRT0449,Griffin Survivor iPhone Case Journey 8 Plus / ...,rugged case with shock dispersion system for i...,29.99,119.899,0,11865403
19214,WAC0253,Wacom Intuos Graphics Tablet S Bluetooth Pista...,small-edge graphics tablet with Bluetooth inte...,99.00,949.898,1,1405
1280,APP0856,Apple iPhone 6 128GB Gold,New Free iPhone 6 128GB (MG4E2QL / A).,899.00,8.989.937,0,NaN
8261,PAC1581,"Apple iMac 21.5 ""Core i5 3.1GHz 4K Retina | 16...",Desktop computer iMac 21.5-inch 3.1GHz Core i5...,2689.00,22.379.906,0,1282
12741,PAC1475,OWC Mercury Elite Pro Dual RAID FW800 / USB3 |...,OWC Mercury Pro Dual + 8TB (2x4TB) Hard Drives...,422.97,3.281.786,1,11935397
2897,JAB0043,Jabra Sport Coach Wireless Headset for iPhone ...,Headphones and Dolby intelligent voice system ...,119.95,999.896,1,5384
15254,LAC0180-A,Open - 1TB LaCie Rugged USB 3.0 Thunderbolt,portable hard Thunderbolt and USB 3.0 Mac and ...,159.99,1.108.329,0,11935397
13754,OWC0168-A,Open - expansion Kit OWC Aura SSD 480GB 6G Mac...,480GB SSD expansion for MacBook Air 11-inch an...,362.99,282.742,0,1298

So we were correct, over 90% of the data in this column is corrupt. There's no point deleting all of these rows, then we would barely have a products table. Instead, as it's only this column that appears to be very untrustworthy, we will delete the column.

In [88]:
products_cl = products_df.drop(columns=["promo_price"])

In [89]:
products_cl.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9992 entries, 0 to 19325
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sku       9992 non-null   object
 1   name      9992 non-null   object
 2   desc      9992 non-null   object
 3   price     9992 non-null   float64
 4   in_stock  9992 non-null   int64
 5   type      9946 non-null   object
dtypes: float64(1), int64(1), object(4)
memory usage: 546.4+ KB

Obviously, there's now no need to convert `promo_price` to a numerical datatype

Don't forget to download/save your new DataFrames. Also, give them an obvious name, so that you know they are the cleaned version and not the original DataFrame.

In [90]:
from google.colab import files

orders_cl.to_csv("orders_cl.csv", index=False)
files.download("orders_cl.csv")

orderlines_cl.to_csv("orderlines_cl.csv", index=False)
files.download("orderlines_cl.csv")

products_cl.to_csv("products_cl.csv", index=False)
files.download("products_cl.csv")

In [91]:
from google.colab import drive
drive.mount('/content/drive')

orders_cl.to_csv("/content/drive/MyDrive/orders_cl.csv", index=False)
orderlines_cl.to_csv("/content/drive/MyDrive/orderlines_cl.csv", index=False)
products_cl.to_csv("/content/drive/MyDrive/products_cl.csv", index=False)

Mounted at /content/drive

In [ ]:
url = "https://drive.google.com/file/d/1_JJj8BVRWyXVUZyA4CSyooWqKKdaAUKc/view?usp=sharing"
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
brands= pd.read_csv(path)